version: '3'
services:
  android:
    build: .
    ports:
      - "6080:6080"  # Для доступа к VNC
      - "5554:5554"  # Для ADB
      - "5555:5555"  # Для ADB
    environment:
      - DEVICE=Samsung Galaxy S10
    volumes:
      - ./screenshot.png:/root/screenshot.png